// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Rvw
Rcpp::DataFrame Rvw(SEXP args);
RcppExport SEXP RVowpalWabbit_Rvw(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(Rvw(args));
    return rcpp_result_gen;
END_RCPP
}
